### ISSUE TITLE
Test Far Sight into Burrowing Mine

### ISSUE THREAD

**Issue by jleclanche** [jleclanche/fireplace#10]
Source: https://pay.reddit.com/r/hearthstone/comments/2s3pnn/so_the_game_just_crashedbugged_after_my_opponent/

> I used brewmaster to re-play my Iron Juggernaut earlier in the game. My opponent used far sight and drew 2 burrowing mines (on the same draw), giving me lethal and what would have won me the game. Instead I am sitting here waiting for my win, haha.

**Comment by NightKev** [comment]
```python
def test_far_sight_into_burrowing_mine():
	game = prepare_game()
	game.player1.discard_hand()
	game.player1.deck.clear()
	game.player1.give("GVG_056t").shuffle_into_deck()
	game.player1.give("GVG_056t").shuffle_into_deck()
	game.player1.give("CS2_053").play()
	assert game.player1.hero.health == 30 - 10 - 10 - 1
	assert not game.player1.hand
```
?

**Comment by jleclanche** [comment]
I never did it because I didn't want to deal with the fatigue tick, fwiw
