### ISSUE TITLE
Testing: expected exceptions

### ISSUE THREAD

**Issue by beheh** [jleclanche/fireplace#115]
Expected exceptions are necessary for some tests (usually for ensuring that the game ends):
- testing hero deaths in general
- Jaraxxus + Repentance + Snipe (#17)
- Jaraxxus + Sacrifical Pact

**Comment by jleclanche** [comment]
If we put those in a separate file, that file can use py.test.

**Comment by jleclanche** [comment]
Done in dd6aca323cd20b1ea7ae12f4e285bd1803c1a8c7.
