### ISSUE TITLE
How to check if an enchantment is an aura

### ISSUE THREAD

**Issue by hstoner009** [jleclanche/fireplace#118]
Hey,

This is a question and not an issue. I was wondering what is the best way to check if an enchantment (i.e., NEW1_033o) is an aura or not. I tried looking at the corresponding minion card_id; however, I hit the following:

For Leokk 
print(Card("NEW1_033").aura) # false

For Mech Warper
print(Card("GVG_006").aura) # true

So is there a more direct way to check if the enchantment is an aura? Thank you for any help!

**Comment by jleclanche** [comment]
If it's in play, you can check the `buff.aura_source`attribute, then you know it comes from an aura.

There is no way to know whether an enchantment ID is the one of an aura, but you could iterate through all the cards and look in the `aura` attribute, look for the enchantment ID.

**Comment by hstoner009** [comment]
Cool thanks for the tip. One thing that I noticed is that Leokk "NEW1_033" one of the companions that comes from the hunter card Animal Companion did not make the aura list. I think it should be an aura card as it looks like you implemented the aura attribute in the classic/hunter.py file

    for card in cards.cardlist:
        if card == "NEW1_033" :
            print("i see leokk")
        try :
            if Card(card).aura :
                print(card,getattr(cards, card))
        except:
            pass

only gave me 

EX1_508 Grimscale Oracle
NAX2_05 Worshipper
EX1_608 Sorcerer's Apprentice
NAX14_03 Frozen Champion
BRMA03_3H Moira Bronzebeard
EX1_315 Summoning Portal
GVG_095 Goblin Sapper
BRMA14_7 Electron
CS2_222 Stormwind Champion
DS1_175 Timber Wolf
NAX2_05H Worshipper
EX1_591 Auchenai Soulpriest
CS2_227 Venture Co. Mercenary
EX1_616 Mana Wraith
FP1_017 Nerub'ar Weblord
EX1_507 Murloc Warleader
GVG_013 Cogmaster
GVG_122 Wee Spellstopper
NEW1_027 Southsea Captain
i see leokk # <------------------------------ no aura
EX1_565 Flametongue Totem
CS2_122 Raid Leader
GVG_006 Mechwarper
GVG_024 Cogmaster's Wrench
EX1_076 Pint-Sized Summoner
GVG_021 Mal'Ganis
GVG_068a Metabolized Magic
EX1_162 Dire Wolf Alpha
BRMA03_3 Moira Bronzebeard
BRMA14_9 Magmatron
FP1_031 Baron Rivendare
GVG_067a Metabolized Magic
