### ISSUE TITLE
Fix Anub'ar Ambusher/Cult Master interaction

### ISSUE THREAD

**Issue by beheh** [jleclanche/fireplace#126]
The interaction should be ([video here](https://www.youtube.com/watch?v=3xS3LtA2q8M) and [here](https://www.youtube.com/watch?v=4sHHQQbPJIM#t=8m55s)):
- if Cult Master was played first: Ambusher dies, Cult Master draws a card, Cult Master is bounced
- if Ambusher was played first: Ambusher dies, Cult Master is bounced (no card draw)

Currently a card is always drawn.

Test case:

``` python
def test_anubar_ambusher_cult_master():
    game = prepare_game()
    game.player1.discard_hand()
    cultmaster1 = game.player1.summon("EX1_595")
    ambusher1 = game.player1.summon("FP1_026")
    assert len(game.player1.hand) == 0
    ambusher1.destroy()
    assert len(game.player1.hand) == 2
    assert cultmaster1 in game.player1.hand
    game.end_turn(); game.end_turn()

    game.player1.discard_hand()
    ambusher2 = game.player1.summon("FP1_026")
    cultmaster2 = game.player1.summon("EX1_595")
    assert len(game.player1.hand) == 0
    ambusher2.destroy()
    assert len(game.player1.hand) == 1
    assert cultmaster2 in game.player1.hand
```

**Comment by jleclanche** [comment]
This is, between other things, a problem with the death ordering in fireplace which is unimplemented. A played order stack needs to be implemented.

**Comment by beheh** [comment]
Shouldn't this simply be correct if we call observers in the order they were added (=order of play)? I'm not sure how Fireplace currently does it, and why it shouldn't consider order of play.

**Comment by jleclanche** [comment]
yes

**Comment by shinoi2** [comment]
fixed
