### ISSUE TITLE
Anima Golem Mind Control bug

### ISSUE THREAD

**Issue by jleclanche** [jleclanche/fireplace#13]
https://www.reddit.com/r/hearthstone/comments/2vys5e/bug_with_anima_golem/

**Comment by anka-213** [comment]
Apparently not reproducible:
* https://www.reddit.com/r/hearthstone/comments/2vys5e/bug_with_anima_golem/com67wo
* https://www.reddit.com/r/hearthstone/comments/2vys5e/bug_with_anima_golem/comilto
