### ISSUE TITLE
Mana related card enchantments should be detached on play()

### ISSUE THREAD

**Issue by oftc-ftw** [jleclanche/fireplace#177]
>     <Patashu> so when you play a minion from the hand
>     <Patashu> Hearthstone keeps all non mana cost related enchantments attached
>     <Patashu> (lets bolvar and mistcaller work)
>     <Patashu> but detaches all mana cost related enchantments
>     <Patashu> and mana cost related auras stop reaching the minion that's in play

So, for example playing Recombobulator on a Molten Giant (cost 20) should always result in another Molten Giant.

See also #176.

**Comment by jleclanche** [comment]
They're not enchantments, they're attribute scripts. This is the 2nd part of the aura rewrite, which requires having Refresh scripts for cost in an in-hand only state.

**Comment by oftc-ftw** [comment]
I'm sorry, this is still happening (hero is at 20 HP):

    [fireplace.entity]: Player1 plays <Minion ('Recombobulator')>
    [fireplace.card]: <Minion ('Recombobulator')> moves from <Zone.HAND: 3> to <Zone.PLAY: 1>
    [fireplace.entity]: Activating <Minion ('Recombobulator')> action targeting <Minion ('Molten Giant')>
    [fireplace.actions]: <Minion ('Recombobulator')> triggering <TargetedAction: Morph(CARD=RandomCardPicker({'type': <CardType.MINION: 4>, 'cost': Attr(<TARGET>,     <GameTag.COST: 48>), 'collectible': True}))> targeting [<Minion ('Molten Giant')>]
    [fireplace.actions]: Morphing <Minion ('Molten Giant')> into <Minion ('Varian Wrynn')>
    [fireplace.entity]: <Minion ('Molten Giant')> is removed from the field
    [fireplace.card]: <Minion ('Molten Giant')> moves from <Zone.PLAY: 1> to <Zone.SETASIDE: 6>
    [fireplace.card]: <Minion ('Varian Wrynn')> moves from <Zone.SETASIDE: 6> to <Zone.PLAY: 1>
    [fireplace.actions]: <Minion ('Recombobulator')> triggering <TargetedAction: Destroy()> targeting [<Minion ('Recombobulator')>]
    [fireplace.entity]: Marking <Minion ('Recombobulator')> for imminent death
    [fireplace.game]: Scheduling death for <Minion ('Recombobulator')>
    [fireplace.entity]: <Minion ('Recombobulator')> is removed from the field
    [fireplace.card]: <Minion ('Recombobulator')> moves from <Zone.PLAY: 1> to <Zone.GRAVEYARD: 4>
    [fireplace.actions]: Processing Death for <Minion ('Recombobulator')>
    Traceback (most recent call last):
      File "test_main.py", line 5866, in <module>
        main()
      File "test_main.py", line 5861, in main
        f()
      File "test_main.py", line 3853, in test_recombobulator_molten
        assert game.player1.field[0].cost == 20
    AssertionError

Varian Wrynn is a 10 mana minion.

**Comment by jleclanche** [comment]
Will look into it but it's probably not the same issue. Keep discussion in the PR :)
