### ISSUE TITLE
Conceal + Alarm-o-bot: Enchantment tries to destroy itself a second time

### ISSUE THREAD

**Issue by beheh** [jleclanche/fireplace#186]
Playing Alarm-o-bot and Conceal on it, with a minion in hand, the following error happens at the beginning of the next turn:

```pytb
self = <Enchantment ('Concealed')>, zone = <Zone.REMOVEDFROMGAME: 5>

    def _set_zone(self, zone):
            if zone == Zone.PLAY:
                    self.owner.slots.append(self)
            elif zone == Zone.REMOVEDFROMGAME:
>                   self.owner.slots.remove(self)
E                   ValueError: list.remove(x): x not in list

../fireplace/card.py:691: ValueError
```

The [full log](https://gist.githubusercontent.com/beheh/1f7af0a1498fd0e37931/raw/ffa2808a687b84e06078838091a7273d897eb6e8/gistfile1.txt) shows, that Conceal is trying to destroy itself a second time, after it has already been destroyed by Alarm-o-bots.

Test case:
```python
def test_conceal_alarmobot():
	game = prepare_empty_game()
	alarmobot = game.player1.give("EX1_006")
	alarmobot.play()
	conceal = game.player1.give("EX1_128")
	conceal.play()
	game.player1.give(WISP)
	game.end_turn(); game.end_turn()

	assert alarmobot in game.player1.hand
	assert wisp in game.player1.field
```

Interestingly this error does not happen when bouncing a concealed minion and waiting out two turns.

**Comment by beheh** [comment]
This is also happening with Nightmare + Alarm-o-bot.

**Comment by jleclanche** [comment]
Should no longer happen with conceal since the changes, but if it can be reproduced with Nightmare i'll have a look.

**Comment by beheh** [comment]
I'll write a test for that as well and PR both.
