### ISSUE TITLE
Eye for an Eye: endless loop

### ISSUE THREAD

**Issue by beheh** [jleclanche/fireplace#187]
An endless loop will occur when both players have Eye for an Eye as secrets.

[Full log](https://gist.githubusercontent.com/beheh/9ec018f3455669f00b36/raw/df81eb28bce01692405c642fb70d7c6386c89d1a/gistfile1.txt)

**Comment by jleclanche** [comment]
This is two different issues. Reveal() should happen first, and secrets shouldn't trigger on the opponent's turn.

**Comment by beheh** [comment]
So, currently all Secrets manually do `*something*, Reveal(SELF)`. Either we flip them manually everywhere, or we do it differently, since I guess every secret is revealed after something occurs.

**Comment by beheh** [comment]
Not triggering secrets on own turn is tracked at #123.
