### ISSUE TITLE
Call Pet: error when no card to draw (fatigue)

### ISSUE THREAD

**Issue by beheh** [jleclanche/fireplace#189]
```python
# Call Pet
class GVG_017:
	# TODO
	def play(self):
		card = self.controller.draw()
		if card.type == CardType.MINION and card.race == Race.BEAST:
			self.buff(card, "GVG_017e")
```

This could be probably be rewritten with DSL.

**Comment by jleclanche** [comment]
This would need a `DRAWN` shortcut to implement this in the DSL, which I kinda want to do anyway (Also needed by Gnomish Experimenter; Similar to King's Elekk)
