### ISSUE TITLE
issue with enrage mechanic

### ISSUE THREAD

**Issue by hstoner009** [jleclanche/fireplace#19]
Hi, I am new to your code but I am having some issues getting the attack from enrages from showing up. For example, I was creating an Amani Berserker (CardID=EX1_393) for player1 and player2 and having one attack the other.

```py
    game = prepare_game(WARLOCK, WARLOCK)
    amani1 = game.currentPlayer.give("EX1_393")
    amani1.play()
    game.currentPlayer.field.append(amani1)
    game.endTurn()

    amani2 = game.currentPlayer.give("EX1_393")
    amani2.play()
    game.currentPlayer.field.append(amani2)
    game.endTurn()        

    print(amani2.atk,amani2.extraAtk,amani2.health)
>> 2 0 3
    amani1.attack(amani2)
    print(amani2.atk,amani2.extraAtk,amani2.health)
>> 2 0 1
    print(amani2.slots)
>> [<Enrage ('Enrage Buff')>]

    game.endTurn()
```

I would have expected the amani2.extraAtk to pick up the Atk=3 in the Enrage class.

**Comment by jleclanche** [comment]
Is this on master? I recently rewrote the enrage system.

**Comment by jleclanche** [comment]
As a sidenote, you're not supposed to manually append units to the field. That happens automatically when you play() the entity.

**Comment by jleclanche** [comment]
Ah, I see the issue. The enrage triggers too early, so the defending minion is killed by the enrage :) I'll get this fixed, thank you.

**Comment by hstoner009** [comment]
In card.py change to this.

self._enrage = Enrage(id=None, data=self.data.Enrage)

**Comment by jleclanche** [comment]
Fixed. Take a look [at the test](https://github.com/jleclanche/fireplace/commit/719995728a4abbe8ef0d489b2b74104a0cd78e80) for an idea of how playing the cards should look.

**Comment by jleclanche** [comment]
@hstoner009 I just realized I did not push the rewritten enrage system to master, so it's quite a bit different now. You'll have to update the submodules and `./bootstrap.sh` again.
