### ISSUE TITLE
webspinner deathrattle issue

### ISSUE THREAD

**Issue by hstoner009** [jleclanche/fireplace#21]
Webspinner FP1_011 in the enUS.xml does not contain an entourage list for its deathrattle, so the random summon will error out on selecting random from an empty list. I think the webspinner needs to generate a list of "collectible" beasts instead.

**Comment by jleclanche** [comment]
Damn. It used to contain an entourage list: https://github.com/jleclanche/hearthstone-data/blob/f38e1a1aab6bf25fe7288719ebc7924f0bd8932b/TextAsset/FP1_011.xml

They must have removed it with GVG when they introduced unstable portal and the like.

**Comment by jleclanche** [comment]
@hstoner009 All fixed. I implemented `fireplace.cards.filter()` to allow filtering by all attributes available in CardXML.
