### ISSUE TITLE
Implement remaining LoE cards

### ISSUE THREAD

**Issue by beheh** [jleclanche/fireplace#219]
# Wing 1

- [x] Djinni of Zephyrs
- [x] Anubisath Sentinel
- [x] Summoning Stone
- [x] Rumbling Elemental
- [x] Sacred Trial
- [x] Ancient Shade
- [x] Reno Jackson
- [x] Obsidian Destroyer
- [x] Jeweled Scarab
- [x] Dark Peddler

# Wing 2

- [x] Excavated Evil
- [x] Brann Bronzebeard
- [x] Keeper of Uldaman
- [x] Tunnel Trog
- [x] Unearthed Raptor
- [x] Reliquary Seeker
- [x] Mounted Raptor
- [x] Tomb Spider
- [x] Ethereal Conjurer

# Wing 3

- [x] Huge Toad
- [x] Anyfin Can Happen
- [x] Jungle Moonkin
- [x] Everyfin is Awesome
- [x] Entomb
- [x] Dart Trap
- [x] Naga Sea Witch
- ~~Pit Snake~~ (same as Emperor Kobra)
- [x] Gorillabot A-3

# Wing 4

- [x] Fossilized Devilsaur
- [x] Wobbling Runts
- [x] Eerie Statue
- [x] Desert Camel
- [x] Tomb Pillager
- [x] Cursed Blade
- [x] Curse of Rafaam
- [x] Animated Armor
- [x] Tomb Pillager
- [x] Elise Starseeker
- [x] Museum Curator
- [x] Raven Idol
- [x] Arch-Thief Rafaam

**Comment by jleclanche** [comment]
Ey we're done.
