### ISSUE TITLE
Aura doesn't update after copying via Mirror Entity

### ISSUE THREAD

**Issue by Meerkov** [jleclanche/fireplace#221]
The following test will fail because the aura is still attached to the copied minion, so it still has 8 max_health.

``` python
def test_mirror_entity_aura():  
    game = prepare_game()
    game.end_turn()
    game.player2.give("CS2_222").play() # Stormwind Champion
    game.end_turn()

    mirror = game.player1.give("EX1_294")
    mirror.play()
    game.end_turn()

    # Mirror entity copies the exact nature of the card when it hits the field.
    blademaster = game.player2.give("CS2_181")
    blademaster.play()
    assert len(game.player1.field) == 1
    assert len(game.player2.field) == 2
    assert game.player1.field[0].health == 4
    assert game.player1.field[0].max_health == 7
    assert game.player2.field[1].health == 4
    assert game.player2.field[1].max_health == 8
```

**Comment by beheh** [comment]
Small hint: if you add `python` behind the \`\`\` when opening your code block, you get syntax highlighting.

**Comment by beheh** [comment]
Wait, are you sure this is supposed to happen? After the blademaster is copied it loses the Stormwind Champion aura, so it's `max_health` should fall back to 7.

**Comment by beheh** [comment]
This has to do with `ExactCopy` copying the Enchantment over to the new minion, but not appending it to the `active_aura_buffs` list if the original one was there. Therefore the aura is not checked for removal in subsequent `refresh_aura` calls.

**Comment by beheh** [comment]
This has to do with `ExactCopy` copying the Enchantment over to the new minion, but not appending it to the `active_aura_buffs` list if the original one was there. Therefore the aura is not checked for removal in subsequent `refresh_aura` calls.

**Comment by beheh** [comment]
I've done a implementation at [beheh/fireplace/secretaura](https://github.com/jleclanche/fireplace/compare/master...beheh:secretaura). Note that I also had to copy the `buff.tick` attribute manually - this can be replaced once we have a good fix for #188.

**Comment by jleclanche** [comment]
@beheh You should give this another shot now that aura updates happen at the right time.

**Comment by jleclanche** [comment]
I think this might be fixed now since the aura rewrite.

**Comment by NightKev** [comment]
Nope, not fixed.
