### ISSUE TITLE
Counterspell counters overload cost

### ISSUE THREAD

**Issue by Meerkov** [jleclanche/fireplace#222]
In the recent patch, overload was changed to be part of the spell cost, not part of the effect. Therefore, counterspell currently is doing it wrong.

**Comment by Meerkov** [comment]
def tst_counterspell():
		game = prepare_game()
		counterspell = game.player1.give("EX1_287")
		counterspell.play()
		game.end_turn()
	
		game.player2.give(WISP).play()
		assert counterspell in game.player1.secrets
		bolt = game.player2.give("EX1_238")
		bolt.play(target=game.player1.hero)
		assert not game.player1.secrets
		assert game.player2.used_mana == 1
		assert game.player2.overloaded == 1 # Overload is part of the manacost now.
		assert game.player1.hero.health == 30

**Comment by beheh** [comment]
This has been confirmed to be a bug by Ben Brode has therefore been reverted.
