### ISSUE TITLE
Missing Auras

### ISSUE THREAD

**Issue by hstoner009** [jleclanche/fireplace#23]
Hi,

I think there may be a few auras that are not implemented yet (not sure if it was intentional). I ran the following code to check for cards with AURA=1 without an associated aura card.

    import fireplace.cards
    game = prepare_game()
    for cardid in fireplace.cards.filter(collectible=True) :
        if Card(cardid).aura and not Card(cardid).data.auras:
            card = Card(cardid)
            print(cardid)   

It looks like most are there except for the following :

GVG_095 = Goblin Sapper
EX1_591 = Auchenai Soulpriest
GVG_024 = Cogmaster's Wrench
GVG_122 = Wee Spellstopper
GVG_013 = Cogmaster

It seems like the Soulpriest aura may require some work to rebroadcast DAMAGE instead of HEAL (i.e., infinite death combo with soulpriest + mistress of pain). In addition, "+ spell damage" appears to boost the heal "damage" when this aura is active.

**Comment by jleclanche** [comment]
Yes you're correct, not all of them are implemented yet.

However, the AURA tag is not as accurate as it passes itself to be. Goblin Sapper and Cogmaster's Wrench are unlikely to be implemented as auras. 

I know how to do soulpriest, I've been putting it off though. But it shouldn't cause much trouble. A rebroadcast should make spell damage work just fine with it, and the mistress of pain combo should work fine (and raise an exception as soon as the hero is at 0hp. Worth noting that this isn't really what should happen, I still need to implement separate death processing).
