### ISSUE TITLE
Spellpower doubling is actually +100%, not x2

### ISSUE THREAD

**Issue by Meerkov** [jleclanche/fireplace#234]
If a player has 2 Prophet Velen in play, then their spell damage and healing is x4. Right now this is coded such that you can only get x2.

https://www.youtube.com/watch?v=1Zav6Ubx3X0

**Comment by jleclanche** [comment]
That doesn't sound right, do you have a test to prove it?

**Comment by Meerkov** [comment]
My mistake, it's incorrect still, but in a different way. Each "double" is actually +100% damage in the current implementation.


def test_prophet_velen_2():
	game = prepare_game(PRIEST, PRIEST)

	expected_health = 30
	assert game.player2.hero.health == expected_health
	assert game.player1.healing_double == 0
	assert game.player1.hero_power_double == 0
	assert game.player1.spellpower_double == 0
	velen1 = game.player1.give("EX1_350")
	velen1.play()
	game.end_turn(); game.end_turn()
	velen2 = game.player1.give("EX1_350")
	velen2.play()
	assert game.player1.healing_double == 2
	assert game.player1.hero_power_double == 2
	assert game.player1.spellpower_double == 2

	game.player1.give(MOONFIRE).play(target=game.player2.hero)
	expected_health -= 4 * 1
	assert game.player2.hero.health == expected_health

	game.player1.give(MOONFIRE).play(target=game.player2.hero)
	expected_health -= 4 * 1
	assert game.player2.hero.health == expected_health

	game.player1.hero.power.use(target=game.player2.hero)
	expected_health += 4 * 2
	assert game.player2.hero.health == expected_health
	game.end_turn(); game.end_turn()

	kobold = game.current_player.give(KOBOLD_GEOMANCER)
	kobold.play()
	game.player1.give(MOONFIRE).play(target=game.player2.hero)
	expected_health -= 4 * (1 + 1)
	assert game.player2.hero.health == expected_health

**Comment by Meerkov** [comment]
It should be multiplied by 1 bitshift left by the current number of doublers.

**Comment by beheh** [comment]
Working on this at [beheh/fireplace/velen](https://github.com/beheh/fireplace/tree/velen). We still need a test for squaring hero power damage (e.g. Mage with double Velen).

**Comment by beheh** [comment]
We should also check the interaction with Arcane Blast.
