### ISSUE TITLE
Arcane Blast should not double its own base damage

### ISSUE THREAD

**Issue by beheh** [jleclanche/fireplace#238]
Arcane Blast currently deals:
- 4 damage without Spellpower increase
- 6 damage with +1 Spellpower
- 8 damage with +2 Spellpower

It should deal:
- 2 damage without Spellpower increase
- 4 damage with +1 Spellpower (2 + 1*2)
- 6 damage with +2 Spellpower (2 + 2*2)

**Comment by beheh** [comment]
[Test case](https://github.com/jleclanche/fireplace/compare/master...beheh:test_arcane_blast).

**Comment by beheh** [comment]
We should also add a test for Prophet Velen/Arcane Blasst interaction.

**Comment by beheh** [comment]
The problem is here that we defer damage amplification to controller.

What should be happening is something like:

```python
# calculate the actual additional spellpower
spellpower = self.spellpower
if receives_double_spelldamage_bonus:
   spellpower *= 2
# add spellpower to base damage
amount = base_damage + spellpower
# double the full damage amount when Velen is in play
amount <<= spellpower_double
```

**Comment by jleclanche** [comment]
Fixed?

**Comment by beheh** [comment]
No, Arcane Blast still deals 4 damage with no spell power on board.

**Comment by shinoi2** [comment]
fixed
