### ISSUE TITLE
battlecry with empty targets

### ISSUE THREAD

**Issue by hstoner009** [jleclanche/fireplace#24]
Minions with battlecries that target minions can be played without a target if none are present.

def test_empty_shattered() :
    game = prepare_game()
    shattered = game.player1.give("EX1_019")
    shattered.play()
    game.endTurn()

However, the following test leads to the error: 

AttributeError: 'NoneType' object has no attribute 'buffs'

I think having a target == None check in the utils.py for buffTarget would enable these battlecry minions to be played with an empty target.

**Comment by jleclanche** [comment]
Fixed. This was more elaborate than that because we try very hard to make sure the user's input is correct. The problem was three-fold:

 - hasTarget() with `REQ_TARGET_IF_AVAILABLE` wasn't implemented correctly and would always claim there's a target (fixed in 2847a50a46c4b276e238114411b20e1804ece5bf)
 - That same hasTarget() check was happening too late in the chain: by that point, the cleric was already on the board and would count itself in the targets (which is normal because cleric doesn't have `REQ_NONSELF_TARGET`). That's fixed in fc338f47f4c4d986f759c2329c5eb490bc7b17e0 by implementing `GameTag.CARD_TARGET`, which I needed to do anyway.
 - Finally, despite all that, the battlecry would still happen even without a target. That's fixed in 4d35bc595b876d782acdc5e68f1755258225fd8b and I added a test for it.

**Comment by hstoner009** [comment]
Based on the full_test.py code for iterating through a minion's attackable target list, I tried the following test:

    game = prepare_game()
    shattered = game.player1.give("EX1_019")
    mech = game.player1.give("GVG_103")
    flametongue = game.player1.give("EX1_565")
    shattered.play()
    mech.play()
    flametongue.play()
    
    game.endTurn(); game.endTurn();

    for minion in game.player1.field :
        if minion.canAttack() :
            print(minion,minion.hasTarget(),minion.targets)

I would have expected all minions to not have a target; however, I get the following output:

Shattered Sun Cleric True [<Minion ('Shattered Sun Cleric')>, <Minion ('Micro Machine')>, <Minion ('Flametongue Totem')>]
Micro Machine False [<Minion ('Shattered Sun Cleric')>, <Minion ('Micro Machine')>, <Minion ('Flametongue Totem')>, <Hero ("Gul'dan")>, <Hero ("Gul'dan")>]

Seems like the Shattered Sun Cleric's hasTarget() returns True and appears to have a different target list than the Micro Machine, could this be related to the recent hasTarget fix? Let me know if there's a problem with my approach to creating an attackable target list for an attacking minion. Thanks!

**Comment by hstoner009** [comment]
I was taking a look at your test cases to see the best way to obtain a list of attackable targets for a minion and it looks like the minion.targets may be the correct list if filtered on the opposing controller. However, when I ran the following code, I think the hero targets may be missing for some minions.

    game = prepare_game()
    shattered1 = game.player1.give("EX1_019")
    mech1 = game.player1.give("GVG_103")
    flametongue1 = game.player1.give("EX1_565")
    shattered1.play()
    mech1.play()
    flametongue1.play()
    game.endTurn();
    mech2 = game.player2.give("GVG_103")
    mech2.play()
    game.endTurn();

    for minion in game.player1.field :
        if minion.canAttack() :
            print(minion,minion.targets)

I would expect that the shattered sun cleric and micro machine will have the same targets list after they are played since they are both simple attacking minions. However, the output looks like the following :

Shattered Sun Cleric [<Minion ('Shattered Sun Cleric')>, <Minion ('Micro Machine')>, <Minion ('Flametongue Totem')>]
Micro Machine [<Minion ('Shattered Sun Cleric')>, <Minion ('Micro Machine')>, <Minion ('Flametongue Totem')>, <Minion ('Micro Machine')>, <Hero ("Gul'dan")>, <Hero ('Jaina Proudmoore')>]

Could this be related to the recent fix related to battlecry targets? In addition, if you have a better suggestion to obtain a list of attackable targets for a given minion, any help would be appreciated. Thanks!

**Comment by jleclanche** [comment]
`minion.targets` should be correct. Thanks, I'll look into this.

**Comment by jleclanche** [comment]
@hstoner009 Done, .targets should now work property.

**Comment by jleclanche** [comment]
@hstoner009 By the way, you can look in `.attackTargets` as well now. These are always the targets that a card can theoretically attack (so you can look at it for cards that havent been played yet, for example).
