### ISSUE TITLE
aura destroy issues

### ISSUE THREAD

**Issue by hstoner009** [jleclanche/fireplace#25]
Hi,

I am currently running the following test case as I was hitting some issues with aura removes. In the test case, I created two Timber Wolfs for player1 and had player2 moonfire both.  

    game = prepare_game()
    timber1 = game.player1.give("DS1_175")
    timber2 = game.player1.give("DS1_175")
    timber1.play()
    timber2.play()
    game.endTurn();
    moonfire1 = game.player2.give("CS2_008") 
    moonfire2 = game.player2.give("CS2_008")
    print([card.atk for card in game.player1.field])
    moonfire1.play(timber1)
    print([card.atk for card in game.player1.field])
    moonfire2.play(timber2)

During the second moonfire, I get a ValueError during the aura destroy. Currently trying to see if I can characterize the error further. Let me know if you need more information or if I may have set up the test case incorrectly. Thanks!

**Comment by jleclanche** [comment]
Good catch. When an entity that had an aura from another entity died, it didn't clean up its buffs properly - and when the time to clean up said aura came, things would go bad. Fixed.
