### ISSUE TITLE
card played error

### ISSUE THREAD

**Issue by hstoner009** [jleclanche/fireplace#26]
Hi,

Running a test with secretkeeper and seems to run into a CARD_PLAYED error:

    game = prepare_game()
    secretkeeper = game.player1.give("EX1_080")
    secretkeeper.play()
    mirror = game.player2.give("CS2_027")
    mirror.play()

TypeError: CARD_PLAYED() takes 2 positional arguments but 3 were given.

**Comment by jleclanche** [comment]
Mirror Entity is not implemented yet. Most secrets aren't; mostly because I want them to be very correct, which means testing a lot of edge cases, so I keep putting it off :)

https://github.com/jleclanche/fireplace/wiki/Cards-TODO

**Comment by hstoner009** [comment]
I think it was a mirror image (not mirror entity) that I was casting. The issue that I was hitting seems to be the number of arguments being passed into the CARD_PLAYED function in secretkeeper from the broadcast.

**Comment by hstoner009** [comment]
Nevermind, it looks like the CARD_PLAYED agrument signature for secretkeeper should have just had player in it as well, like most of the other cards.

**Comment by jleclanche** [comment]
I'll look into it.

**Comment by hstoner009** [comment]
Looks like it was just a simple oversight. I think secretkeeper is supposed to just have player in the arguments.

# Secretkeeper
class EX1_080:
	def CARD_PLAYED(self, player, card): # add player into here
		if card.tags.get(GameTag.SECRET):
			self.buff(self, "EX1_080e")

**Comment by jleclanche** [comment]
@hstoner009 Fixed, thank you. The buff was broken as well, good thing you caught it. :)
