### ISSUE TITLE
bootstrap.py fails with AttributeError: 'CardXML' object has no attribute 'forgetful'

### ISSUE THREAD

**Issue by pkappler** [jleclanche/fireplace#262]
./bootstrap
Fetching data files from https://github.com/HearthSim/hs-data.git
Cloning into './scripts/hs-data'...
remote: Counting objects: 25, done.        
remote: Compressing objects: 100% (25/25), done.        
remote: Total 25 (delta 2), reused 18 (delta 0), pack-reused 0        
Unpacking objects: 100% (25/25), done.
Checking connectivity... done.
Metabolized Magic: Setting <GameTag.ATK: 47> = 2
Nefarian: Adding hero power 'TBA01_5'
Ancient Watcher: Setting <GameTag.CANT_ATTACK: 227> = True
Ragnaros the Firelord: Adding hero power 'TBA01_6'
Omnotron Defense System: Adding hero power 'BRMA14_2'
Instructor Razuvious: Adding hero power 'NAX7_03H'
Yarrr!: Setting <GameTag.HEALTH: 45> = 1
Yarrr!: Setting <GameTag.ATK: 47> = 1
Gluth: Adding hero power 'NAX12_02'
Traceback (most recent call last):
  File "./scripts/bootstrap.py", line 196, in <module>
    main()
  File "./scripts/bootstrap.py", line 166, in main
    if not card.forgetful and id != "GVG_112":
AttributeError: 'CardXML' object has no attribute 'forgetful'

**Comment by jleclanche** [comment]
You need to update python-hearthstone (`pip install --upgrade -r requirements.txt`)
