### ISSUE TITLE
Minion damaged attacking opposing hero

### ISSUE THREAD

**Issue by hstoner009** [jleclanche/fireplace#27]
Hi,

I ran the following test:

    game = prepare_game()
    waraxe = game.player1.give("CS2_106")
    waraxe.play()
    game.endTurn()
    tinker = game.player2.give("GVG_102")
    print(tinker.health)
    tinker.attack(game.player1.hero)
    print(tinker.health)

tinker health is 3 and then 0. It should be 3 and then 3 as player2's minion should not receive damage from player1s weapon. However, the weapon correctly does not lose durability due to the tinker's attack.

**Comment by jleclanche** [comment]
Weapon sheathing is not implemented. I'll work on it soon.

**Comment by hstoner009** [comment]
Oh okay. Cool!

**Comment by jleclanche** [comment]
@hstoner009 Done!

By the way, if you are interested in fireplace, you really should swing by our IRC channel (#hearthsim on Freenode). It's not exclusive to fireplace but development happens there.
