### ISSUE TITLE
SI:7 agent always requires a target

### ISSUE THREAD

**Issue by beheh** [jleclanche/fireplace#271]
SI:7 Agent should not require a target if combo is not active. Observed via Kettle.

**Comment by beheh** [comment]
Hm, the following test seems to work: Maybe the options aren't correctly serialized by Kettle?

```python
def test_si7_agent():
	game = prepare_game()
	agent = game.player1.give("EX1_134")
	assert not agent.has_target()
	wisp = game.player1.give(WISP)
	wisp.play()
	assert agent.has_target()
	game.end_turn(); game.end_turn()

	assert not agent.has_target()
```

**Comment by beheh** [comment]
Also happening with Blackwing Corruptor.

**Comment by jleclanche** [comment]
@beheh Have you ever tracked this down? Does it still happen? if the tests don't break, maybe it's a problem with how kettle serializes it...

**Comment by shinoi2** [comment]
Kettle is deprecated
