### ISSUE TITLE
Tinkmaster Overspark moves transformed minion to end of field

### ISSUE THREAD

**Issue by beheh** [jleclanche/fireplace#276]
The transformed minion always ends up at the last ZONE_POSITION when using Tinkmaster Overpark. Maybe this is happens with morphing in general.

**Comment by smallnamespace** [comment]
@beheh Assuming your commits fixed this -- closing.

**Comment by beheh** [comment]
No, this commit is not in the master branch. It's an implementation for #281, but that can't land because it doesn't solve the problem.
