### ISSUE TITLE
Anub'arak can't be re-played properly after its Deathrattle

### ISSUE THREAD

**Issue by PattuX** [jleclanche/fireplace#283]
Observed in Joust.

I got Anub'arak out of a Portal, played him and Destroyed him with my own BGH.
The Nerubian was summoned correctly and Anub'arak was returned to hand but its cost was 6 mana again instead of the intended 9. (maybe #177?)
However, after trying to re-play him, i got a Nerubian and Anub'arak was moved to the far right of my hand, so i assume he got destroyed immediately when played.

**Comment by jleclanche** [comment]
i guess the TO_BE_DESTROYED tag isn't cleared out. fun.

**Comment by beheh** [comment]
Also, the Unstable Portal enchantment did not get removed - but this was probably fixed by 6ca236cdb8970225f74f9200e9129f33a78fdbd2.

**Comment by PattuX** [comment]
No, I'm sure I observed it after that fix as I opened this issue right after it happened.

**Comment by beheh** [comment]
I might not have immediatley updated Kettle server-side - I don't have a hook setup yet.

**Comment by beheh** [comment]
Where do we want to reset `to_be_destroyed`? In `Bounce()`, ` _schedule_death` or `Death()`?

**Comment by PattuX** [comment]
```_schedule_death``` or ```Death()``` as it might also happen with Malorne or other stuff that doesn't necessarily get bounced.

**Comment by beheh** [comment]
No, Malorne is a copy IIRC. @jleclanche?

**Comment by jleclanche** [comment]
Malorne, IIRC, is a copy in fireplace because it used to be that way in HS. They changed it now, so we should change it too.
