### ISSUE TITLE
Mimiron's Head has wrong trigger conditions

### ISSUE THREAD

**Issue by PattuX** [jleclanche/fireplace#284]
(Count(FRIENDLY_MINIONS + MECH) >= 4) 
should be >= 3

And in
Destroy(FRIENDLY_MINIONS + MECH), Deaths(), Summon(CONTROLLER, "GVG_111t")
the Mech Condition is only linked with Destroy(...) atm. Deaths() and Summon(...) are always executed, creating a (mostly useless) forced death face and giving you a V-07-TR-0N.

**Comment by PattuX** [comment]
Are you sure that fix works? 
Python might interpret (Destroy(FRIENDLY_MINIONS + MECH), Deaths(), Summon(CONTROLLER, "GVG_111t")) as a tupel.

**Comment by beheh** [comment]
Yeah, that's how awesome the DSL is, you can queue in sequence :-)
