### ISSUE TITLE
some minor issues

### ISSUE THREAD

**Issue by hstoner009** [jleclanche/fireplace#29]
Hey,

The new tag push seems to be pretty good although I hit a few minor issues during my testing. Below, I posted some quick fixes that seemed to make my code work again as a couple of the attributes seem to be missing in the latest commit:

1) In card.py, the Character class should probably be initialized with self.numAttacks = 0 (hit a few errors not finding that attribute during Minion attacks). The BaseCard class should probably have self.secret = False (secretkeeper will error when a non-secret was played)

2) In player.py the Player class should probably be initialized with self.usedMana = 0, self.combo = False, self.minionsPlayedThisTurn = 0.

3) In targeting.py, I was hitting an issue where a weapon's race was being checked so maybe checking that the 'race' attribute is available or the target is a Minion before checking for race is needed. 

4) In cards/utils.py, healHero(amount) should be applied to self.controller.hero rather than hero.

5) In cards/classic/druid.py, the `buffSelf(self, "**")` should be changed to `buffSelf("**")` for Claw and Bite; and replace character to target in self.hit(target,5) in Starfire.

6) In cards/classic/warrior.py, the Frothing Beserker action should be OWN_DAMAGE not DAMAGE

7) In cards/gvg/hunter.py, metaltooth leaper is buffing all entities, should only do mechs
```python
	def action(self) :
		for minion in self.controller.field:
			if minion is not self and minion.race == Race.MECHANICAL :
				self.buff(minion, "GVG_048e")
```

I also implemented a few cards (probably not in the most ideal way), so if you would like to use them  as a starting point, please feel free:

8) In cards/classic/paladin.py, the repentance enchantment was missing
```python
# Repentance
class EX1_379e:
       HEALTH = lambda i: 1
```

9) In cards/gvg/hunter.py, maybe you can add Call Pet. It also required an enchantment (similar to Summoning Portal that is in the extras/missing_cards.py) to reduce cost by 4 on the beast draw.
```python
# Call Pet
class GVG_017:
	def action(self):
		card = self.controller.draw()
			if card.type == CardType.MINION and card.race == Race.BEAST :
				self.buff(card, "GVG_017e")
```
Missing buff for call pet
```python
GVG_017e = {
	GameTag.CARDNAME: "Call Pet Buff",
	GameTag.CARDTYPE: CardType.ENCHANTMENT,
	GameTag.COST: -4,
}
```

10) In cards/gvg/neutral_common.py, maybe you can add tinkertown technician.
```python
# Tinkertown Technician
class GVG_102:
	def action(self):
		if self.poweredUp:
			self.buff(self, "GVG_102e")
			self.controller.give(random.choice(self.data.entourage))
```
11) Added a few gvg rogue card implementations

```python
from ..utils import *


##
# Minions

# Goblin Auto-Barber
class GVG_023:
	def action(self):
		if self.controller.hero.weapon:
			self.buff(self.controller.hero.weapon, "GVG_023a")
		
# One-eyed Cheat
class GVG_025:
	def OWN_MINION_SUMMON(self, minion):
		if minion.race == Race.PIRATE:
			self.stealthed = True
			
# Iron Sensei
class GVG_027:
	def OWN_TURN_END(self):
		own_mechs = [minion for minion in self.controller.field if minion.race == Race.MECHANICAL] 
		if own_mechs :
			self.buff(random.choice(own_mechs),"GVG_027e")
			

# Trade Prince Gallywix
class GVG_028:
	def CARD_PLAYED(self, player, card):
		if player == self.controller.opponent and card.type == CardType.SPELL:
			self.controller.give(card.id)
			player.give("GVG_028t")

# Gallywix's Coin
class GVG_028t:
	def action(self):
		self.controller.tempMana += 1
			
##
# Spells

# Sabotage
class GVG_047:
	def action(self):
		if self.controller.opponent.field :
			random.choice(self.controller.opponent.field).destroy()
	def combo(self):
		if self.controller.opponent.field :
			random.choice(self.controller.opponent.field).destroy()
		if self.controller.opponent.hero.weapon:
			self.controller.opponent.hero.weapon.destroy()


# Tinker's Sharpsword Oil
class GVG_022:
	def action(self):
		if self.controller.hero.weapon :
			self.buff(self.controller.hero.weapon, "GVG_022a")
	def combo(self):
		if self.controller.hero.weapon :
			self.buff(self.controller.hero.weapon, "GVG_022a")
		if self.controller.field :
			self.buff(random.choice(self.controller.field), "GVG_022b")
```

which required these additions in buffs.py 

```python
# Iron Sensei
GVG_027e = {
	GameTag.ATK: 2,
	GameTag.HEALTH: 2
}

# Tinker's Sharpsword Oil
GVG_022a = buff(atk=3)
GVG_022b = buff(atk=3)

# Goblin Auto-Barber
GVG_023a = buff(atk=1)
```

**Comment by hstoner009** [comment]
iron sensei is apparently a mech, so you have to remove self from the random.choice list.

**Comment by jleclanche** [comment]
Thanks, will fix when I'm done with the current cleanups
