### ISSUE TITLE
Curse of Rafaam should not be affected by Spell Power/Velen

### ISSUE THREAD

**Issue by beheh** [jleclanche/fireplace#306]

**Comment by jleclanche** [comment]
Eh? Yes it should be.

**Comment by beheh** [comment]
It actually is not ingame, see http://hearthstone.gamepedia.com/Curse_of_Rafaam (Notes).

**Comment by jleclanche** [comment]
Right, but that's because it has the ImmuneToSpellpower tag. So I don't think this is an issue?

**Comment by beheh** [comment]
Yeah, you're right. I just want to write a test for it.

**Comment by smallnamespace** [comment]
I'll take this on

**Comment by beheh** [comment]
Ah, great I completely forgot - that's even my test.
