### ISSUE TITLE
knife juggler issue

### ISSUE THREAD

**Issue by hstoner009** [jleclanche/fireplace#31]
Knife juggler should not hit when it is summoned. In addition, the potential targets has a typo
```python
# Knife Juggler
class NEW1_019:
	def OWN_MINION_SUMMON(self, minion):
		if minion is not self :
			self.hit(random.choice(self.controller.getTargets(TARGET_ENEMY_CHARACTERS)), 1)
```
On the same note, mass dispell also has a typo
```python
# Mass Dispel
class EX1_626:
	def action(self):
		for target in self.controller.getTargets(TARGET_ENEMY_MINIONS):
			target.silence()
		self.controller.draw()
```

**Comment by jleclanche** [comment]
Damn, this is an issue I had with tidecaller as well... minions really shouldn't receive their own summon event.

**Comment by jleclanche** [comment]
This is fixed in the new events API.

**Comment by jleclanche** [comment]
I wrote this post to give an overview of what changed and why, by the way:

http://hearthsim.info/New-site-new-blog-new-events-api/
