### ISSUE TITLE
Excavated Evil - SELF not on entity list at Copy() evaluation time

### ISSUE THREAD

**Issue by smallnamespace** [jleclanche/fireplace#315]
Ran into this while rewriting the selectors -- there's no problem right now because `SELF` was rewritten to always return source, but should probably figure out why it wasn't on the entity list.

**Comment by shinoi2** [comment]
Original: After the spell is played, its zone is Zone.PLAY, which is not in any entity list.
Now: After the spell is played, its zone is Zone.GRAVEYARD, so its in the graveyard list
