### ISSUE TITLE
Polyglot bootstrap doesn't work in windows

### ISSUE THREAD

**Issue by smallnamespace** [jleclanche/fireplace#321]
Unfortunately `CMD.EXE` seems to require `.bat` or `.cmd` or `.bmt` file extensions.

@jleclanche Are you comfortable giving the polyglot script a `.bat` extension? Otherwise it might be preferable to just call the right script directly.

**Comment by jleclanche** [comment]
I've had people successfully run it on windows..

**Comment by synap5e** [comment]
This is correct ARAIK - windows basically uses the extension instead of an executable bit.
To run bootstrap on windows one must use `run < bootstrap`

**Comment by smallnamespace** [comment]
Yeah, requiring `cmd < bootstrap` essentially defeats the purpose of the polyglot script, since POSIX and WIndows users now need a different invocation.

**Comment by jleclanche** [comment]
Closing, bootstrap's gone.
