### ISSUE TITLE
Create Intelligent Agent 

### ISSUE THREAD

**Issue by rm596** [jleclanche/fireplace#332]
Hi all

I'm master student doing is thesis.
I need a simulator where I can create an intelligent agent that learn how to play hearthstone.

I'm no familiar with this engine, so please can you give me some info if its possible and how did I install the engine on my windows machine.

Please help

**Comment by smallnamespace** [comment]
@rm596 

Have you tried following the directions [here](https://github.com/jleclanche/fireplace/blob/master/README.md) and [here](https://github.com/jleclanche/fireplace/wiki/Developer-Quick-Start)? If you run into any difficulties, please let me know.

**Comment by smallnamespace** [comment]
Closing unless there's anything actionable
