### ISSUE TITLE
Kettle does not track SETASIDE

### ISSUE THREAD

**Issue by beheh** [jleclanche/fireplace#333]
Kettle does not send tag changes from entities in SETASIDE anymore, resulting (for example) in played spell being stuck in a players hand.

**Comment by djkaty** [comment]
It does now :)

**Comment by beheh** [comment]
This is still happening for me on the master branch. Which commit do you think fixed it?

**Comment by beheh** [comment]
Hm, I see that setaside is in __iter__. Investigating further.
