### ISSUE TITLE
"Minions that died this game" effects track dead minions, rather than deaths

### ISSUE THREAD

**Issue by edk0** [jleclanche/fireplace#371]
See ca7d5a9830443911eba52ff100fd4a09cf869461.

Hearthstone considers _death the event_ different from _death the state_. Effects like Resurrect and N'Zoth track the former. In fireplace they don't.

See:
* https://youtu.be/5Pn7NM0Uz7U
* https://youtu.be/Cc0xYeqVvrE?t=389

**Comment by jleclanche** [comment]
For the time being, I'm considering this wontfix for various reasons as explained earlier on IRC.
