### ISSUE TITLE
API inconsistency with hero power and entities

### ISSUE THREAD

**Issue by djkaty** [jleclanche/fireplace#382]
Most entities use:

```
if entity.is_playable:
  entity.play(...)
```

Hero powers use:

```
if hero.power.is_usable():
  hero.power.use(...)
```

Why does this disparity exist? Can it be merged?

**Comment by jleclanche** [comment]
As we discussed on IRC a while back, the disparity is due to the different paths use() and play() take (Battlecry vs Activate). Right now, it's intended. Maybe we'll change it down the line.
