### ISSUE TITLE
Test Gruul-Ragnaros interaction

### ISSUE THREAD

**Issue by jleclanche** [jleclanche/fireplace#4]

**Comment by tonyyyye** [comment]
I get it right, but it depends on the target ragnaros hits. 

def test_gruul():
        game = prepare_game()
        gruul = game.current_player.give("NEW1_038")
        gruul.play()
        game.current_player.opponent.summon("EX1_298")
        assert gruul.atk == 7
        assert gruul.health == 7
        assert not gruul.buffs
        game.end_turn()

        assert gruul.buffs
        assert gruul.atk == 8
        assert gruul.health == 8
        game.end_turn()

        assert gruul.atk == 9
        assert gruul.health == 1
 
Maybe a trigger filter can solve this. When it is the end of the ragnaros' turn, if it hits gruul then assert.
