### ISSUE TITLE
Attack restrictions

### ISSUE THREAD

**Issue by thomaseding** [jleclanche/fireplace#402]
It looks like BHG does not care about the target's attack. Likewise for: Shadow Word Pain, Shadow Word Death, Cabal Shadow Priest, and Shadow Madness. 

Shadow Word Horror looks fine and is the basis for my report.

**Comment by jleclanche** [comment]
What makes you say that? Did you test it?

**Comment by thomaseding** [comment]
I've never ran your code, but comparing the card implementation to that of cards like "Shadow Word Horror" and "Hobgoblin", they clearly do not spell out their restrictions on attack, where as these two cards do.

**Comment by jleclanche** [comment]
See this page for explanation on how play requirements work:

https://github.com/jleclanche/fireplace/wiki/PlayRequirements

Shadow Word: Horror does not use play requirements (it's a runtime script).

Thanks for the report!
