### ISSUE TITLE
RandomTotem 

### ISSUE THREAD

**Issue by snowypowers** [jleclanche/fireplace#412]
Hi,

RandomTotem() summons a random totem but right now it is not restricted to *basic* totems. 

However, the cards that are using it right now can only summon *basic* totems. 

Thus, I would like to ask which way is better:

- Create and use new method RandomBasicTotem()

- Update RandomTotem() to summon only *basic* totems and think about it when Blizz decides to do random totem from all totems.

Thanks!

PS: I don't have a idea for a good implementation for random basic totem. Anyone?

**Comment by jleclanche** [comment]
There's a `RandomID` class defined in `dsl/random_picker.py`. You can use that to implement it.

I would add something like this in `utils.py`:

`RandomBasicTotem = lambda *args: RandomID("CS2_050", "CS2_051", "CS2_052", "NEW1_009")`

Note that Totemic Call uses Entourage, so you shouldn't use that for anything else than Tuskarr Totemic.

**Comment by snowypowers** [comment]
Tuskarr currently uses RandomTotem() too. It is not using entourage.

Anyway looks like a good implementation. I will go ahead and add it to `utils.py` 

I will change `Wicked WitchDoctor` and `Tuskarr Totemic` to use RandomBasicTotem` instead.

**Comment by jleclanche** [comment]
It's not really a picker, it's a helper based on a picker :P
