### ISSUE TITLE
KeyError: 'Collectible' when running initial tests (python 3.5, error attached)

### ISSUE THREAD

**Issue by wanqizhu** [jleclanche/fireplace#414]
Hey,

I followed the [quick start guide](https://github.com/jleclanche/fireplace/wiki/Developer-Quick-Start) but ran into a stream of errors. Seems to be something off with enum.py in utils, but I can't figure out what's wrong. My packages are all up to date.

This seems like a really cool project, and I'd appreciate any help to get me started! Thanks!

`python -m pytest
============================= test session starts ==============================
platform darwin -- Python 3.5.1, pytest-3.0.4, py-1.4.31, pluggy-0.4.0
rootdir: /Users/wanqi/Desktop/Academics/Programs/projects/Hearthstone Engine/fireplace, inifile: 
collected 0 items / 20 errors 

==================================== ERRORS ====================================
______________ ERROR collecting tests/test_auchenai_soulpriest.py ______________
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/enum.py:266: in __getattr__
    return cls._member_map_[name]
E   KeyError: 'Collectible'

During handling of the above exception, another exception occurred:
test_auchenai_soulpriest.py:1: in <module>
    from utils import *
utils.py:3: in <module>
    import fireplace.cards
../fireplace/cards/__init__.py:6: in <module>
    from ..rules import POISONOUS
../fireplace/rules.py:4: in <module>
    from .cards.utils import *
../fireplace/cards/utils.py:4: in <module>
    from ..aura import Refresh
../fireplace/aura.py:2: in <module>
    from .managers import CardManager
../fireplace/managers.py:224: in <module>
    GameTag.Collectible: None,
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/enum.py:268: in __getattr__
    raise AttributeError(name) from None
E   AttributeError: Collectible
___________________ ERROR collecting tests/test_blackrock.py ___________________
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/enum.py:266: in __getattr__
    return cls._member_map_[name]
E   KeyError: 'Collectible'

During handling of the above exception, another exception occurred:
test_blackrock.py:1: in <module>
    from utils import *
utils.py:3: in <module>
    import fireplace.cards
../fireplace/cards/__init__.py:6: in <module>
    from ..rules import POISONOUS
../fireplace/rules.py:4: in <module>
    from .cards.utils import *
../fireplace/cards/utils.py:4: in <module>
    from ..aura import Refresh
../fireplace/aura.py:2: in <module>
    from .managers import CardManager
../fireplace/managers.py:224: in <module>
    GameTag.Collectible: None,
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/enum.py:268: in __getattr__
    raise AttributeError(name) from None
E   AttributeError: Collectible
`

**Comment by jleclanche** [comment]
I updated the Collectible tag to COLLECTIBLE per a recent HS update. Fixed now.

**Comment by jleclanche** [comment]
Note that the test will probably not pass because of hero power issues - that's due to an update in the game files I'm still working on.

**Comment by wanqizhu** [comment]
Got it, thanks! @jleclanche But I could start simulating w/o using Hero Powers?
