### ISSUE TITLE
Can't get logging to work on Windows

### ISSUE THREAD

**Issue by pixelrebel** [jleclanche/fireplace#419]
Following instructions on the ReadMe, I can get logging to work on a Mac, but not Windows.  

Any tips for troubleshooting this further?  Is there a windows log facility that must also be enabled?

**Comment by jleclanche** [comment]
What's the issue? encoding maybe?

**Comment by pixelrebel** [comment]
Thanks @jleclanche for replying so quickly.  

As it turns out, I'm an idiot.  

I'm almost embarrassed to post this publicly, but when I created the `log.config` file, I didn't realize Windows was hiding the `.txt` extension.  So the file I made was actually named `log.config.txt`.  I wasted about 3 hours on that.  Oh well.  Thanks again!
