### ISSUE TITLE
lightwell

### ISSUE THREAD

**Issue by hstoner009** [jleclanche/fireplace#42]
Lightwell needs a targets empty check so that you do not random.choice with none.

# Lightwell
class EX1_341:
	def OWN_TURN_BEGIN(self):
		targets = [t for t in self.controller.getTargets(TARGET_FRIENDLY_CHARACTERS) if t.damage]
		if targets :
			self.heal(random.choice(targets), 3)

**Comment by jleclanche** [comment]
I'm currently working on the action-based redesign. See
https://github.com/jleclanche/fireplace/commit/59e1a68d96a9049bc7955741e7794d389e2cf9ef
for a preview of what it'll look like.
There's a pretty big amount of work involved but the payoff is massive.
This should fix a lot of these incidental bugs - I caught a lot of broken
cards while working on those, too.

J. Leclanche
