### ISSUE TITLE
question about the code 

### ISSUE THREAD

**Issue by curtank** [jleclanche/fireplace#422]
in the file fireplace/util.py line 182

def play_turn(game: ".game.Game") -> ".game.Game":
....

what dose this mean?or give me a keyword so I can search that.
THANKS

**Comment by jleclanche** [comment]
These are type annotations. See https://docs.python.org/3/library/typing.html

**Comment by jleclanche** [comment]
Swing by our discord channel if you have more questions! https://hearthsim.info/join/
