### ISSUE TITLE
Replay by Joust

### ISSUE THREAD

**Issue by pakxpakx** [jleclanche/fireplace#430]
Is there any way to log the "full game" and replay it in Joust?

**Comment by djdookie** [comment]
I have the same question.

**Comment by jleclanche** [comment]
It's not implemented and would require a lot of work. Feel free to try, but … good luck.

**Comment by djdookie** [comment]
Ok thanks for your quick reply.
Can you tell me how to connect from Joust to the running kettle.py of Fireplace?
Loading a .hsreplay file works fine in Joust for me, same for running fireplace simulations.
I'd like to play against a fireplace AI using Joust.

**Comment by jleclanche** [comment]
None of it works anymore. Joust drag&drop support was dropped a while ago (@beheh might be able to help you find the commit), and kettle has changed a ton.

**Comment by djdookie** [comment]
Ah sorry, Stove went to closed source, not Kettle.
So what's your current way to simulate games using any up-to-date protocols/servers/interfaces/GUIs?
Or did you abandon this stuff completely?

**Comment by jleclanche** [comment]
I can give you access to Stove if you need it for educational purposes to work on simulation. But it too isn't under active development.
I wouldn't say it's abandoned, but the original maintainers of these programs (myself, bert, mischanix, etc) don't have the time to dedicate to Hearthstone anymore and nobody else wanted to take over.

**Comment by djdookie** [comment]
I would really appreciate that!
