### ISSUE TITLE
setuptools is missing from dependencies, python 3.5 is not really supported

### ISSUE THREAD

**Issue by manuel-delverme** [jleclanche/fireplace#435]
setuptools (or wheel?) is missing from dependencies
python 3.5 is not supported by the hearthstone package so fireplace should be bumped up to 3.6

**Comment by tonyyyye** [comment]
i can run under 3.5 provided that the server has installed module hearthstone.

**Comment by manuel-delverme** [comment]
I'll investigate further tonight

**Comment by 75075896** [comment]
As i mentioned in [this issue](https://github.com/jleclanche/fireplace/issues/434), the setup steps may change a little and a python version requirement is now listed as Python 3.5+ in the main page. 
I am not sure if we should add versions to .travis.yml.

**Comment by tonyyyye** [comment]
As i mentioned in this issue, the setup steps may change a little and a python version requirement is now listed as Python 3.5+ in the main page.
I am not sure if we should add versions to .travis.yml.
