### ISSUE TITLE
Willing to add unittest code

### ISSUE THREAD

**Issue by tonyyyye** [jleclanche/fireplace#436]
Just jumped from hearthbreaker.
Find that unittest is missing from fireplace and i have already added some.
Is that needed for this project?

**Comment by tonyyyye** [comment]
@jleclanche if so, i can add some to this project.

**Comment by tonyyyye** [comment]
to do so, simply add unittest.TestCase  subclass  and add some cases to the original ones.

**Comment by jleclanche** [comment]
Hi @tonyyyye, sorry for the slow reply

Tests are welcome, yes. Fireplace is unmaintained because I haven't really had the time for it since I moved full time on HearthSim, but if you swing by [Discord](https://discord.gg/hearthsim), I'll be happy to help you with it.
