### ISSUE TITLE
druid morph issues

### ISSUE THREAD

**Issue by hstoner009** [jleclanche/fireplace#45]
Hey,

I was seeing some issues with druid choice cards such as Druid of the Claw (EX1_165). It looks like once you make the choice to like EX1_165b which is a Spell card, you then call MORPH on the spell card. However, Spells do not have the morph attribute only Minions do. I encountered this issue on an earlier commit but I think it should still happen on the latest build. Let me know thanks!

**Comment by jleclanche** [comment]
Shouldn't Druif of the Fang exhibit that issue? There's a test for it (`test_druid_of_the_fang`)

**Comment by hstoner009** [comment]
Let me update my code to your latest build. But I believe the difference is that the morph is being applied to the druid of the fang card. On the other hand, druid of the claw requires suboptions which branch into two "spell" cards. The morph is being called on these spell cards rather than the base minion card.

**Comment by jleclanche** [comment]
Ah, yeah, I see what you mean. I'll address this when I'm done with the events revamp.

**Comment by hstoner009** [comment]
I think if chosen cards keep track of their creator card. Then calling the morph on the creator can do the trick.

**Comment by hstoner009** [comment]
Hey,

So I think I was running this test which ran into the self.morph issue:

    game = prepare_game(DRUID,DRUID)
    dclaw = game.player1.give("EX1_165")
    game.player1.play(dclaw,None,"EX1_165b")
    print([card.health for card in game.player1.field])

Temporary fix that I was using was adding self.creator in the chosen block of play(...) and then morphing the creator for each druid of the claw suboption spell.

Also, you may want to add ironbeak owl to neutral_common in classic:

# Ironbeak Owl
class CS2_203:
	action = [Silence(TARGET)]

As well as imp-losion to gvg/warlock

# Implosion
class GVG_045:
	def action(self, target):
		damage=random.choice((2, 3, 4))
		self.hit(target, damage)
		for i in range(damage) :
			self.controller.summon("GVG_045t")

I apologize for still using the old style of actions.

**Comment by jleclanche** [comment]
Thanks. I'll try to look at all this soon, I'm currently working on some server stuff.

**Comment by jleclanche** [comment]
@hstoner009 Fixed, sorry for the long delay!
