### ISSUE TITLE
Secrets with Lord Jaraxxus

### ISSUE THREAD

**Issue by tonyyyye** [jleclanche/fireplace#450]
Some secret may have specific trigger for Lord Jaraxxus("EX1_323") such as

>  Redemption("EX1_136") 
>  Snipe("EX1_609")
>  Effigy("AT_002")
>  Mirror Entity("EX1_294")

 I don't actually have this card in Blizzard Client, but as of pytest with Redemption the results in my env may not be all right.
Here are some test results in game
[Chinese screenshot](https://tieba.baidu.com/p/4132167792?red_tag=2917284460
)

Anyone who possesses these cards may add a comment.

**Comment by jleclanche** [comment]
IIRC I got Jaraxxus working with all the classic secrets and there's extensive tests against it. Mirror entity has extra checks against it.

**Comment by tonyyyye** [comment]
Yes I have seen it in code, but with no specific modification for other secrets such as Redemption with which I tested and got wrong assert.
Sorry I can't load test code here.

**Comment by tonyyyye** [comment]
Sorry I mistakenly assumed Repentance as Redemption. 
All the classic secrets seemed good in this way.

**Comment by tonyyyye** [comment]
But a recent test in real game shows that Lord Jaraxxus triggers battlecry regularly, with a 15 health Hero replaced while the 'Explosive Runes' secret does not kill Jaraxxus even when i have added 15+ spell damage.

I did not test with Snipe, but maybe these two cards share the same machenic. 

When using Snipe in pytest case, the hero died.

opponent.summon("EX1_609") # Snipe
opponent.summon("EX1_563") # Malygos
opponent.summon("EX1_563")
opponent.summon("EX1_563")
give("EX1_323").play()

The result triggers fireplace.exceptions.GameOver. 
@jleclanche Maybe we can have a try.

**Comment by tonyyyye** [comment]
I just duelled and got a rest result, which is 'Secrets would not deal any damage to Jaraxxus'

**Comment by tonyyyye** [comment]
http://hs.blizzard.cn/article/23/11229
This is 2017/10/18 patch for CN area.

**Comment by tonyyyye** [comment]
Done with it.  
Plan to do more patches for other secrets.
