### ISSUE TITLE
[test]Missing steps in attack cycle when Truesilver Champion triggers off Shadowboxer

### ISSUE THREAD

**Issue by tonyyyye** [jleclanche/fireplace#452]
[An interesting test with shadowboxer](https://www.hearthpwn.com/forums/hearthstone-general/card-discussion/23874-new-card-shadowboxer?page=2)

I recalled an interesting test the other day and made a pytest case for it.
Somehow it didn't work and I don't know why.

> [fireplace.actions]: <Hero ('Anduin Wrynn')> attacks <Minion ('Wisp')>
> [fireplace.actions]: <Weapon ('Truesilver Champion')> triggers off <Action: Attack(<Attack.ATTACKER>=<Hero ('Anduin Wrynn')>, <Attack.DEFENDER>=<Minion ('Wisp')>)> from <Hero ('Anduin Wrynn')>
> [fireplace.actions]: <Weapon ('Truesilver Champion')> triggering <TargetedAction: Heal(<Heal.AMOUNT>=2)> targeting [<Hero ('Anduin Wrynn')>]
> [fireplace.actions]: <Weapon ('Truesilver Champion')> heals <Hero ('Anduin Wrynn')> for 1
> [fireplace.actions]: <Minion ('Shadowboxer')> triggers off <TargetedAction: Heal(<Heal.AMOUNT>=2)> from <Weapon ('Truesilver Champion')>
> [fireplace.actions]: <Minion ('Shadowboxer')> triggering <TargetedAction: Hit(<Hit.AMOUNT>=1)> targeting [<Minion ('Wisp')>]
> [fireplace.actions]: <Minion ('Shadowboxer')> triggering <TargetedAction: Predamage(<Predamage.AMOUNT>=1)> targeting [<Minion ('Wisp')>]
> [fireplace.actions]: <Minion ('Shadowboxer')> triggering <TargetedAction: Damage()> targeting [<Minion ('Wisp')>]
> [fireplace.actions]: <Hero ('Anduin Wrynn')> triggering <TargetedAction: Hit(<Hit.AMOUNT>=4)> targeting [<Minion ('Wisp')>]
> [fireplace.actions]: <Hero ('Anduin Wrynn')> triggering <TargetedAction: Predamage(<Predamage.AMOUNT>=4)> targeting [<Minion ('Wisp')>]
> [fireplace.actions]: <Hero ('Anduin Wrynn')> triggering <TargetedAction: Damage()> targeting [<Minion ('Wisp')>]

The dead minion is supposed to be removed and attacker can attack again.

**Comment by jleclanche** [comment]
I don't think fireplace has the full attack cycle implemented for situations like these.

**Comment by tonyyyye** [comment]
It is not an issue any more since the recent update of  Shadowboxer  in version 12.0
