### ISSUE TITLE
When Choose Twice, only second choose work.

### ISSUE THREAD

**Issue by shinoi2** [jleclanche/fireplace#454]
Like Branching Paths, Volcanosaur, or some Discover card with Brann Bronzebeard.

**Comment by tonyyyye** [comment]
Yes I reproduced it and here is what i discovered.
`class Battlecry`
 implements actions for battlecry as 
`source.game.main_power(source, actions, target)`

Minion Brann gives it another main_power(), but when it misses Choose (and Index()) as a playable Minion which has
`play(self, target=None, index=None, choose=None):`

This could also be a potential problem for minions with tag **Adapt**.


@shinoi2  Please make me aware it if you have any new ideas about it.

**Comment by tonyyyye** [comment]
Maybe Brann can also work like another way like Mechwarper does.

By this I mean literally the description shows that it's the **Player** who can trigger battlecry twice but acturally only **Cards in hand**, including Minion/Hero/Weapon,  can trigger it.

**Comment by jleclanche** [comment]
This needs to be tested ingame, if possible with an hsreplay file for reference.

**Comment by tonyyyye** [comment]
It was tested. 
In the program, the first choice is not finished with choice when the second comes out.
Don't know if a combined Discover method can be called, or an alternative ‘choose First/Second/Third’ parameter (not the card name) can be supplied.

**Comment by tonyyyye** [comment]
I did not test with Arch-Thief Rafaam("LOE_092") under the current environment and i think it's a special Discover with the only three cards offered.

This special battlecry will supposedly trigger twice when Brann is on board.
Since I decomposed this minion, can you help us with this test? @shinoi2
