### ISSUE TITLE
Silence bug 

### ISSUE THREAD

**Issue by shinoi2** [jleclanche/fireplace#463]
```
    def test_silence():
        game = prepare_game()
        minion = game.player1.summon("CS2_182")
        assert minion.health == 5
        game.player1.give("CS2_004").play(target=minion)
        assert minion.health == 7
        game.player1.give("CS2_004").play(target=minion)
        game.player1.give("GVG_015").play(target=minion)
        assert minion.health == 4
        game.player1.give("CS2_203").play(target=minion)
        assert minion.health == 4
```
In fireplace, this minion.health is 2.

**Comment by tonyyyye** [comment]
I tried to reproduce it and got the logs below:

> Clearing buffs from <Minion ('Chillwind Yeti')>
> <Enchantment ('Power Word: Shield')> moves from <Zone.PLAY: 1> to <Zone.REMOVEDFROMGAME: 5>
> <Enchantment ('Power Word: Shield')> moves from <Zone.PLAY: 1> to <Zone.REMOVEDFROMGAME: 5>

and

> [fireplace.actions]: Silencing <TargetedAction: Silence()>
> [fireplace.entity]: Clearing buffs from <Minion ('Chillwind Yeti')>
> [fireplace.card]: <Enchantment ('Power Word: Shield')> moves from <Zone.PLAY: 1> to <Zone.REMOVEDFROMGAME: 5>
> [fireplace.card]: <Enchantment ('Power Word: Shield')> moves from <Zone.PLAY: 1> to <Zone.REMOVEDFROMGAME: 5>



The silence procedure is:

1. broadcast EventListener
2. clear all stored buffs
3. Wipe the event listeners

From this we can make it clear that the minion health is presented as original health + fuffs[]
while the actual health may have a calculation of damage and healing which is missing in fireplace .

In real game, I think, it is a little bit complicated (some of the conclusion need more testing):

1. The buffs for the minion are presented under the buff list (shown by moving over the focus).
2. The Silencing procedure will restore its origin atk whatever buffs it has taken.
3. When the minion is damaged (RAGE/in red), the silence will
    1)set the minion to its default health value when the current health is **no less than**  that of the original one and after being silenced the RAGE tag is removed.
    2)keep the current value and RAGE tag when the current health is **less than** that of the original one.
4. The swap health/atk buff will do as it describes and remove the RAGE tag.
5. When the minion is not damaged, the silence will reset the minion to its original attributes.
TODO
6. Haven't test 'swap h/a in hand' but the original form of 'Swift Messenger'(GIL_528) justified my guess.

**Comment by shinoi2** [comment]
Fixed
