### ISSUE TITLE
small error on rogue.py?

### ISSUE THREAD

**Issue by aharalabMeiji** [jleclanche/fireplace#484]
line 54 in cards.wog.rogue.py
yield Destory(TARGET)->yield Destroy(TARGET) ?

**Comment by aharalabMeiji** [comment]
line 902, action.py
		difference = max(0, amount - len(target.controller.hand))# <- target.hand

**Comment by aharalabMeiji** [comment]
Another question:
in fireplace.actions.py, line 903, at DrawUntil.do() method,  in most cases 'target' is a player, but sometimes it is a Minion, but Minion does not have hand, it occurs ''Minion' object has no attribute 'hand' error.  I think it better to replace target by target.controller.  (if 'target is a player, there are no trouble here.)

**Comment by aharalabMeiji** [comment]
Another question：
About 'Consume Magic'('BT_490')
if a card is this guy and call card.requires_target() then it returns FALSE.  But this guy make a minion silence.  ... ..

**Comment by shinoi2** [comment]
Thank you. I'll fix it as soon as possible.
