### ISSUE TITLE
Truesilver Champion + Explosive Trap

### ISSUE THREAD

**Issue by jleclanche** [jleclanche/fireplace#5]
https://www.reddit.com/r/hearthstone/comments/207lvz/truesilver_champion_explosive_trap_bug_fixed/

> You no longer heal twice with Truesilver when running into an explosive trap. You do still go down to 0 and then go back up to 2 health, but your attack isn't cancelled so you don't heal a second time.

**Comment by NightKev** [comment]
https://www.youtube.com/watch?v=YoafHKc2ZJI

**Comment by jleclanche** [comment]
Guess it was fixed.

**Comment by jleclanche** [comment]
Need to add it in fireplace once the new death system is in.
