### ISSUE TITLE
floating watcher issue

### ISSUE THREAD

**Issue by hstoner009** [jleclanche/fireplace#51]
Hey,

I was testing floating watcher and hit the following error using this test case:

TypeError: <lambda>() takes 3 positional arguments but 4 were given

```python
WATCHER = "GVG_100"
def test_watcher() :
        game = prepare_game(WARLOCK,WARLOCK)
        watcher = game.player1.give(WATCHER)
        watcher.play()
        game.endTurn();game.endTurn()
        assert(watcher.atk==4)
        game.player1.hero.power.play()
        assert(watcher.atk==6)
        assert(watcher.atk==6)
```

I think the lambda function requires 4 arguments (aka lambda self, target, amount, source:). Thanks!

**Comment by hstoner009** [comment]
In addition the order or arguments on the mistress of pain look incorrect. I think it should be:

lambda self, target, amount, source: source is self and [Heal(FRIENDLY_HERO, amount)] or []

This is a merge of the watcher and mistress of pain in 1 test:

        game = prepare_game(WARLOCK,WARLOCK)
        watcher = game.player1.give(WATCHER)
        watcher.play()
        mistress = game.player1.give(MISTRESS)
        game.endTurn();game.endTurn()
        assert(watcher.atk==4)
        game.player1.hero.power.play()
        mistress.play()
        assert(watcher.atk==6)
        assert(game.player1.hero.health==28)
        mistress.attack(game.player2.hero)
        assert(game.player1.hero.health==29)

**Comment by jleclanche** [comment]
Thanks, Ill try to fix them today.

**Comment by hstoner009** [comment]
Floating watcher does not test the order of arguments in the lambda function but mistress of pain will. I think the committed order is incorrect.it should be target,amount,source For both floating watcher and mistress of pain.

**Comment by jleclanche** [comment]
Good catch, not that it matters since the argument is unused :)

**Comment by jleclanche** [comment]
Ill do Mistress of Pain later, i want to take care of a test with Auchenai before.
