### ISSUE TITLE
Cards are compared by card type (id) not by card instance in action matching

### ISSUE THREAD

**Issue by synap5e** [jleclanche/fireplace#65]
When an `EventListener` is checked against an `Action`, cards are considered to be matching by the _type_ (`BaseCard.id`) of the card, not the specific instance of the card.

An example of this would be two of the same card with a `SELF_DAMAGE` listener, where one takes damage. `Action.matches` will return `True` for both cards even if only one has taken damage because both cards match the damaged card.
An example of this behavior with Imp Gang Boss is [here](https://gist.github.com/synap5e/c66eaedce0594c0eca88). In this test a player has 2 Imp Gang Bosses on the field, and one is hit with Fireblast. Instead of one imp being created, the action is triggered for both, and two Imps are created.
As can be seen in the log, the `Summon` action is triggered twice, once for each Gang Boss.

<br>

This is because cards are considered equal if BaseCard.id is equal (same card id). i.e. 
```
game = prepare_game()

WISP = "CS2_231"
wisps = [game.player1.give(WISP)] * 2

print(wisps[0] == wisps[1])
```
Prints `True`

AFAICT this equality is intended based on the fact that `test_mind_vision` asserts that the copied card is equal to the card it copies.

My hacky fix was to change `Action.matches` to compare the `uuid` of cards instead of the cards themselves, but I don't feel I have enough familiarity with the codebase to produce a better solution.

**Comment by jleclanche** [comment]
Thanks a lot! A simple `is` comparison will fix it, yeah. The action matching code is fairly complex though. I'll try to fix it today.

BTW, hop in to the IRC channel (details [here](http://hearthsim.info)) if you are interested in fireplace, it's easier to reach me from there :) Just ping jleclanche.

**Comment by synap5e** [comment]
doh! of course `is` is the answer, silly me. Thanks for the work on fireplace, I'll defiantly check in on the IRC, there seems to be some interesting stuff going on.
