### ISSUE TITLE
Powermace: Verify unable to save minions

### ISSUE THREAD

**Issue by beheh** [jleclanche/fireplace#81]
Add a test for Powermace, to verify that it cannot buff <1 health Mechs:

"Unlike effects such as Avenge and Dark Cultist, Powermace cannot buff a 0 or lower Health Mech and thus save it from dying (if the Powermace trigger and the damage are in the same Phase)."
--[Hearthstone wiki](http://hearthstone.gamepedia.com/Powermace)

**Comment by beheh** [comment]
Implemented in beheh/fireplace@644dc75c0d845ed69e093eb4f11f6566daab22f5. Works with the Explosive Trap fix.

**Comment by jleclanche** [comment]
@beheh I won't be implementing this because this is still undefined in HS.

**Comment by beheh** [comment]
It actually already works, the minion dies immediately with my test case.

**Comment by jleclanche** [comment]
Yeah but that's for a different reason :/

**Comment by beheh** [comment]
Should I remove the test case from the next PR then?
