### ISSUE TITLE
'Minion' object has no attribute 'rarity'

### ISSUE THREAD

**Issue by Ragowit** [jleclanche/fireplace#96]
Got this on my fork, will merge in the latest changes and try again with logging enabled to see if I can reproduce and get some logging info as well.

```
Traceback (most recent call last):
  File "C:\Temp\Python\fireplace\mcts\uct.py", line 551, in UCTPlayGame
    m = UCT(rootstate = state, seconds = 14400, verbose = False)
  File "C:\Temp\Python\fireplace\mcts\uct.py", line 520, in UCT
    while state.GetMoves() != []: # while state is non-terminal
  File "C:\Temp\Python\fireplace\mcts\uct.py", line 366, in GetMoves
    if card.has_target():
  File "C:\Temp\Python\fireplace\fireplace\card.py", line 310, in has_target
    return bool(self.targets)
  File "C:\Temp\Python\fireplace\fireplace\card.py", line 433, in targets
    return super().targets
  File "C:\Temp\Python\fireplace\fireplace\card.py", line 315, in targets
    return [card for card in self.game.characters if is_valid_target(self, card)]
  File "C:\Temp\Python\fireplace\fireplace\card.py", line 315, in <listcomp>
    return [card for card in self.game.characters if is_valid_target(self, card)]
  File "C:\Temp\Python\fireplace\fireplace\targeting.py", line 62, in is_valid_target
    if target.rarity != Rarity.LEGENDARY:
AttributeError: 'Minion' object has no attribute 'rarity'
```

**Comment by Ragowit** [comment]
Got it again, here's the entire log: https://gist.github.com/Ragowit/e170117203206215f707

**Comment by Ragowit** [comment]
Might be because of Ice Block not being implemented yet in Fireplace, close issue?

**Comment by jleclanche** [comment]
I don't think that's why. It's staying open either way.

**Comment by Ragowit** [comment]
Added some more output to see which card it is when erroring out on card.has_target().

Answer: Rend Blackhand

Will try and get the target information as well.

**Comment by Ragowit** [comment]
The target is Flame of Azzinoth.

**Comment by Ragowit** [comment]
In the code so is Illidan Stormrage (who spawns Flame of Azzinoth) set to spawn "EX1_614t". However, "EX1_614t" lacks enumID="203" which is the RARITY. There is another Flame of Azzinoth available with ID "TU4e_002t" that has the enumID="203", but another cardset (enumID="183" of 5 instead of 3).

**Comment by jleclanche** [comment]
That makes more sense. I'll try and figure out a way to fix it.

**Comment by jleclanche** [comment]
BTW that `TU4e_002t` is a tutorial card (from the illidan fight)

**Comment by Ragowit** [comment]
Slime from Sludge Belcher has the same issue.

**Comment by beheh** [comment]
This is due to Rend Blackhands PlayReq.REQ_LEGENDARY_TARGET which tries to access the rarity of all minions. Probably make the requirement (in targeting.py) check for tag existance first, or think of sane tag defaults.
This issue is similar to #105, because we need to think about non-existing tags. I'll buid a test case.
