### ISSUE TITLE
Steamwheedle Sniper missing tag

### ISSUE THREAD

**Issue by hstoner009** [jleclanche/fireplace#97]
Hey,

Ran the following test:

```python
    game = prepare_game(HUNTER, HUNTER)
    steam = game.player1.give("GVG_087")
    steam.play()
```

And received the following error:

```pytb
  File "C:\Python34\lib\site-packages\fireplace-0.1-py3.4.egg\fireplace\managers.py", line 35, in update
    if self.map[k]:
KeyError: <GameTag.STEADY_SHOT_CAN_TARGET: 383>
```

`GameTag.STEADY_SHOT_CAN_TARGET: 383`

Seems like it is a missing game tag.

**Comment by jleclanche** [comment]
Sniper isn't fully implemented yet, I just added the tag to help someone through implementing it but they veered on something else.

That said I'm reconsidering the aura system at the moment, so we'll see what comes from it.

**Comment by jleclanche** [comment]
This should be fixed in the new aura system.
